// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(DbContextApp))]
    [Migration("20260402044726_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.DeliveryRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("DestinationRoomId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("OriginRoomId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex("DestinationRoomId");

                    b.HasIndex("OriginRoomId");

                    b.HasIndex("RequesterId");

                    b.ToTable("delivery_request", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Location", b =>
                {
                    b.Property<string>("RoomId")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.HasKey("RoomId");

                    b.ToTable("location", (string)null);

                    b.HasData(
                        new
                        {
                            RoomId = "A-101",
                            Description = "Emergency Room"
                        },
                        new
                        {
                            RoomId = "LAB-05",
                            Description = "Pathology Lab"
                        });
                });

            modelBuilder.Entity("Backend.Models.Sample", b =>
                {
                    b.Property<string>("SampleUniqueId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("SampleType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("SampleUniqueId");

                    b.HasIndex("RequestId");

                    b.ToTable("sample", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("StaffId");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("Backend.Models.DeliveryRequest", b =>
                {
                    b.HasOne("Backend.Models.Location", "Destination")
                        .WithMany("DestinationRequests")
                        .HasForeignKey("DestinationRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Location", "Origin")
                        .WithMany("OriginRequests")
                        .HasForeignKey("OriginRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Staff", "Staff")
                        .WithMany("DeliveryRequests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Origin");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Backend.Models.Sample", b =>
                {
                    b.HasOne("Backend.Models.DeliveryRequest", "DeliveryRequest")
                        .WithMany("Samples")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryRequest");
                });

            modelBuilder.Entity("Backend.Models.DeliveryRequest", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("Backend.Models.Location", b =>
                {
                    b.Navigation("DestinationRequests");

                    b.Navigation("OriginRequests");
                });

            modelBuilder.Entity("Backend.Models.Staff", b =>
                {
                    b.Navigation("DeliveryRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
