// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(DbContextApp))]
    partial class DbContextAppModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Horse", b =>
                {
                    b.Property<string>("HorseId")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("HorseName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("Registration")
                        .HasColumnType("int");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("HorseId");

                    b.HasIndex("StableId");

                    b.ToTable("Horses");

                    b.HasData(
                        new
                        {
                            HorseId = "horse1",
                            Age = 2,
                            Gender = "C",
                            HorseName = "Warrior",
                            Registration = 11111,
                            StableId = "stable1"
                        },
                        new
                        {
                            HorseId = "horse2",
                            Age = 2,
                            Gender = "F",
                            HorseName = "Conquerer",
                            Registration = 22222,
                            StableId = "stable6"
                        },
                        new
                        {
                            HorseId = "horse3",
                            Age = 3,
                            Gender = "C",
                            HorseName = "Dove of Peace",
                            Registration = 33333,
                            StableId = "stable1"
                        },
                        new
                        {
                            HorseId = "horse4",
                            Age = 3,
                            Gender = "F",
                            HorseName = "Ever Faster",
                            Registration = 44444,
                            StableId = "stable3"
                        },
                        new
                        {
                            HorseId = "horse5",
                            Age = 2,
                            Gender = "C",
                            HorseName = "Slow Winner",
                            Registration = 55555,
                            StableId = "stable3"
                        },
                        new
                        {
                            HorseId = "horse6",
                            Age = 2,
                            Gender = "F",
                            HorseName = "Windrunner",
                            Registration = 66666,
                            StableId = "stable2"
                        },
                        new
                        {
                            HorseId = "horse7",
                            Age = 4,
                            Gender = "M",
                            HorseName = "Catapult",
                            Registration = 77777,
                            StableId = "stable6"
                        },
                        new
                        {
                            HorseId = "horse8",
                            Age = 2,
                            Gender = "C",
                            HorseName = "Flying Force",
                            Registration = 88888,
                            StableId = "stable4"
                        },
                        new
                        {
                            HorseId = "horse9",
                            Age = 2,
                            Gender = "F",
                            HorseName = "Laggard",
                            Registration = 99999,
                            StableId = "stable4"
                        },
                        new
                        {
                            HorseId = "horse10",
                            Age = 6,
                            Gender = "G",
                            HorseName = "Formula One",
                            Registration = 10101,
                            StableId = "stable2"
                        },
                        new
                        {
                            HorseId = "horse11",
                            Age = 3,
                            Gender = "C",
                            HorseName = "Frisky Frolic",
                            Registration = 11011,
                            StableId = "stable4"
                        },
                        new
                        {
                            HorseId = "horse12",
                            Age = 3,
                            Gender = "F",
                            HorseName = "Fantastic",
                            Registration = 12121,
                            StableId = "stable2"
                        },
                        new
                        {
                            HorseId = "horse13",
                            Age = 2,
                            Gender = "C",
                            HorseName = "Midnight",
                            Registration = 13131,
                            StableId = "stable3"
                        },
                        new
                        {
                            HorseId = "horse14",
                            Age = 4,
                            Gender = "S",
                            HorseName = "Running Wild",
                            Registration = 14141,
                            StableId = "stable2"
                        },
                        new
                        {
                            HorseId = "horse15",
                            Age = 3,
                            Gender = "C",
                            HorseName = "FastOffMyFeet",
                            Registration = 15151,
                            StableId = "stable1"
                        },
                        new
                        {
                            HorseId = "horse16",
                            Age = 2,
                            Gender = "C",
                            HorseName = "Slow Poke",
                            Registration = 16161,
                            StableId = "stable3"
                        },
                        new
                        {
                            HorseId = "horse17",
                            Age = 3,
                            Gender = "F",
                            HorseName = "Slinger",
                            Registration = 17171,
                            StableId = "stable2"
                        },
                        new
                        {
                            HorseId = "horse18",
                            Age = 5,
                            Gender = "M",
                            HorseName = "Sublime",
                            Registration = 18181,
                            StableId = "stable6"
                        },
                        new
                        {
                            HorseId = "horse19",
                            Age = 4,
                            Gender = "G",
                            HorseName = "Front Runner",
                            Registration = 19191,
                            StableId = "stable4"
                        },
                        new
                        {
                            HorseId = "horse20",
                            Age = 3,
                            Gender = "C",
                            HorseName = "Night",
                            Registration = 20200,
                            StableId = "stable1"
                        },
                        new
                        {
                            HorseId = "horse21",
                            Age = 3,
                            Gender = "F",
                            HorseName = "Negative",
                            Registration = 21210,
                            StableId = "stable3"
                        },
                        new
                        {
                            HorseId = "horse22",
                            Age = 2,
                            Gender = "C",
                            HorseName = "Lightening",
                            Registration = 22220,
                            StableId = "stable6"
                        },
                        new
                        {
                            HorseId = "horse23",
                            Age = 4,
                            Gender = "G",
                            HorseName = "Lazy Loser",
                            Registration = 23230,
                            StableId = "stable1"
                        },
                        new
                        {
                            HorseId = "horse24",
                            Age = 2,
                            Gender = "C",
                            HorseName = "Leaping Lizard",
                            Registration = 24240,
                            StableId = "stable1"
                        },
                        new
                        {
                            HorseId = "horse25",
                            Age = 3,
                            Gender = "F",
                            HorseName = "Beautiful Brown",
                            Registration = 25250,
                            StableId = "stable6"
                        },
                        new
                        {
                            HorseId = "horse26",
                            Age = 5,
                            Gender = "M",
                            HorseName = "Sick Winner",
                            Registration = 26260,
                            StableId = "stable2"
                        });
                });

            modelBuilder.Entity("Backend.Models.Owner", b =>
                {
                    b.Property<string>("OwnerId")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("FName")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("LName")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            OwnerId = "owner1",
                            FName = "Ahmed",
                            LName = "Saeed"
                        },
                        new
                        {
                            OwnerId = "owner2",
                            FName = "Khalid",
                            LName = "Mohammed"
                        },
                        new
                        {
                            OwnerId = "owner3",
                            FName = "Faisal",
                            LName = "Mohammed"
                        },
                        new
                        {
                            OwnerId = "owner4",
                            FName = "Abdul Rahman",
                            LName = "Fahd"
                        },
                        new
                        {
                            OwnerId = "owner5",
                            FName = "",
                            LName = "Nasr"
                        },
                        new
                        {
                            OwnerId = "owner6",
                            FName = "Sheikh",
                            LName = "Mohammed"
                        },
                        new
                        {
                            OwnerId = "owner7",
                            FName = "Ahmed",
                            LName = "Abed"
                        },
                        new
                        {
                            OwnerId = "owner8",
                            FName = "",
                            LName = "Mashour"
                        },
                        new
                        {
                            OwnerId = "owner9",
                            FName = "Sheikh",
                            LName = "Said"
                        },
                        new
                        {
                            OwnerId = "owner10",
                            FName = "Khan",
                            LName = "Faisal"
                        },
                        new
                        {
                            OwnerId = "owner11",
                            FName = "Mohammed",
                            LName = "Jabr"
                        },
                        new
                        {
                            OwnerId = "owner12",
                            FName = "Mahmood",
                            LName = "Faleh"
                        },
                        new
                        {
                            OwnerId = "owner13",
                            FName = "Mohammed",
                            LName = "Yahya"
                        },
                        new
                        {
                            OwnerId = "owner14",
                            FName = "",
                            LName = "Sulaiman"
                        },
                        new
                        {
                            OwnerId = "owner15",
                            FName = "Ali",
                            LName = "Saeed"
                        },
                        new
                        {
                            OwnerId = "owner16",
                            FName = "Faisal",
                            LName = "Ahmed"
                        },
                        new
                        {
                            OwnerId = "owner17",
                            FName = "Mohammed",
                            LName = "Saud"
                        },
                        new
                        {
                            OwnerId = "owner18",
                            FName = "Mohammed",
                            LName = "Nazir"
                        },
                        new
                        {
                            OwnerId = "owner19",
                            FName = "Fahd",
                            LName = "Saleh"
                        },
                        new
                        {
                            OwnerId = "owner20",
                            FName = "Naeem",
                            LName = "Mohammed"
                        });
                });

            modelBuilder.Entity("Backend.Models.Owns", b =>
                {
                    b.Property<string>("OwnerId")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("HorseId")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("OwnerId", "HorseId");

                    b.HasIndex("HorseId");

                    b.ToTable("Owns", (string)null);

                    b.HasData(
                        new
                        {
                            OwnerId = "owner14",
                            HorseId = "horse1"
                        },
                        new
                        {
                            OwnerId = "owner3",
                            HorseId = "horse2"
                        },
                        new
                        {
                            OwnerId = "owner2",
                            HorseId = "horse3"
                        },
                        new
                        {
                            OwnerId = "owner2",
                            HorseId = "horse4"
                        },
                        new
                        {
                            OwnerId = "owner1",
                            HorseId = "horse5"
                        },
                        new
                        {
                            OwnerId = "owner12",
                            HorseId = "horse5"
                        },
                        new
                        {
                            OwnerId = "owner14",
                            HorseId = "horse5"
                        },
                        new
                        {
                            OwnerId = "owner1",
                            HorseId = "horse6"
                        },
                        new
                        {
                            OwnerId = "owner5",
                            HorseId = "horse6"
                        },
                        new
                        {
                            OwnerId = "owner20",
                            HorseId = "horse7"
                        },
                        new
                        {
                            OwnerId = "owner19",
                            HorseId = "horse8"
                        },
                        new
                        {
                            OwnerId = "owner2",
                            HorseId = "horse9"
                        },
                        new
                        {
                            OwnerId = "owner18",
                            HorseId = "horse10"
                        },
                        new
                        {
                            OwnerId = "owner3",
                            HorseId = "horse10"
                        },
                        new
                        {
                            OwnerId = "owner4",
                            HorseId = "horse11"
                        },
                        new
                        {
                            OwnerId = "owner16",
                            HorseId = "horse12"
                        },
                        new
                        {
                            OwnerId = "owner17",
                            HorseId = "horse13"
                        },
                        new
                        {
                            OwnerId = "owner15",
                            HorseId = "horse14"
                        },
                        new
                        {
                            OwnerId = "owner15",
                            HorseId = "horse15"
                        },
                        new
                        {
                            OwnerId = "owner20",
                            HorseId = "horse16"
                        },
                        new
                        {
                            OwnerId = "owner4",
                            HorseId = "horse17"
                        },
                        new
                        {
                            OwnerId = "owner6",
                            HorseId = "horse19"
                        },
                        new
                        {
                            OwnerId = "owner12",
                            HorseId = "horse20"
                        },
                        new
                        {
                            OwnerId = "owner7",
                            HorseId = "horse21"
                        },
                        new
                        {
                            OwnerId = "owner7",
                            HorseId = "horse22"
                        },
                        new
                        {
                            OwnerId = "owner10",
                            HorseId = "horse23"
                        },
                        new
                        {
                            OwnerId = "owner12",
                            HorseId = "horse24"
                        },
                        new
                        {
                            OwnerId = "owner13",
                            HorseId = "horse25"
                        },
                        new
                        {
                            OwnerId = "owner2",
                            HorseId = "horse26"
                        },
                        new
                        {
                            OwnerId = "owner9",
                            HorseId = "horse23"
                        },
                        new
                        {
                            OwnerId = "owner8",
                            HorseId = "horse18"
                        });
                });

            modelBuilder.Entity("Backend.Models.Race", b =>
                {
                    b.Property<string>("RaceId")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime?>("RaceDate")
                        .HasColumnType("date");

                    b.Property<string>("RaceName")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<TimeSpan?>("RaceTime")
                        .HasColumnType("time");

                    b.Property<string>("TrackName")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("RaceId");

                    b.HasIndex("TrackName");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            RaceId = "race1",
                            RaceDate = new DateTime(2007, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "Kings Cup",
                            RaceTime = new TimeSpan(0, 14, 0, 0, 0),
                            TrackName = "Riyadh"
                        },
                        new
                        {
                            RaceId = "race2",
                            RaceDate = new DateTime(2007, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "2-year-old fillies",
                            RaceTime = new TimeSpan(0, 13, 0, 0, 0),
                            TrackName = "Doha"
                        },
                        new
                        {
                            RaceId = "race3",
                            RaceDate = new DateTime(2007, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "2-year-old colts",
                            RaceTime = new TimeSpan(0, 13, 30, 0, 0),
                            TrackName = "Doha"
                        },
                        new
                        {
                            RaceId = "race4",
                            RaceDate = new DateTime(2007, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "Handicap",
                            RaceTime = new TimeSpan(0, 12, 0, 0, 0),
                            TrackName = "Doha"
                        },
                        new
                        {
                            RaceId = "race5",
                            RaceDate = new DateTime(2007, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "Claiming Stake",
                            RaceTime = new TimeSpan(0, 12, 30, 0, 0),
                            TrackName = "Sharjah"
                        },
                        new
                        {
                            RaceId = "race6",
                            RaceDate = new DateTime(2007, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "3-year-old fillies",
                            RaceTime = new TimeSpan(0, 12, 30, 0, 0),
                            TrackName = "Jubail"
                        },
                        new
                        {
                            RaceId = "race7",
                            RaceDate = new DateTime(2007, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "Handicap",
                            RaceTime = new TimeSpan(0, 9, 30, 0, 0),
                            TrackName = "Jubail"
                        },
                        new
                        {
                            RaceId = "race8",
                            RaceDate = new DateTime(2007, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "2-year-old colts",
                            RaceTime = new TimeSpan(0, 10, 30, 0, 0),
                            TrackName = "Riyadh"
                        },
                        new
                        {
                            RaceId = "race9",
                            RaceDate = new DateTime(2007, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "2-year-old fillies",
                            RaceTime = new TimeSpan(0, 11, 30, 0, 0),
                            TrackName = "Jubail"
                        },
                        new
                        {
                            RaceId = "race10",
                            RaceDate = new DateTime(2007, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "Claiming Stake",
                            RaceTime = new TimeSpan(0, 12, 30, 0, 0),
                            TrackName = "Sharjah"
                        },
                        new
                        {
                            RaceId = "race11",
                            RaceDate = new DateTime(2007, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "3-year-old fillies",
                            RaceTime = new TimeSpan(0, 10, 30, 0, 0),
                            TrackName = "Dubai"
                        },
                        new
                        {
                            RaceId = "race12",
                            RaceDate = new DateTime(2007, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "Handicap",
                            RaceTime = new TimeSpan(0, 11, 30, 0, 0),
                            TrackName = "Yanbu"
                        },
                        new
                        {
                            RaceId = "race13",
                            RaceDate = new DateTime(2007, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "3-year-old fillies",
                            RaceTime = new TimeSpan(0, 11, 0, 0, 0),
                            TrackName = "Yanbu"
                        },
                        new
                        {
                            RaceId = "race14",
                            RaceDate = new DateTime(2007, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "Handicap",
                            RaceTime = new TimeSpan(0, 10, 0, 0, 0),
                            TrackName = "Dhahran"
                        },
                        new
                        {
                            RaceId = "race15",
                            RaceDate = new DateTime(2007, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "3-year-old colts",
                            RaceTime = new TimeSpan(0, 15, 0, 0, 0),
                            TrackName = "Dubai"
                        },
                        new
                        {
                            RaceId = "race16",
                            RaceDate = new DateTime(2007, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "Claiming Stake",
                            RaceTime = new TimeSpan(0, 14, 30, 0, 0),
                            TrackName = "Yanbu"
                        },
                        new
                        {
                            RaceId = "race17",
                            RaceDate = new DateTime(2007, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "Handicap",
                            RaceTime = new TimeSpan(0, 13, 0, 0, 0),
                            TrackName = "Doha"
                        },
                        new
                        {
                            RaceId = "race18",
                            RaceDate = new DateTime(2007, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "3-year-old fillies",
                            RaceTime = new TimeSpan(0, 8, 0, 0, 0),
                            TrackName = "Sharjah"
                        },
                        new
                        {
                            RaceId = "race19",
                            RaceDate = new DateTime(2007, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "2-year-old colts",
                            RaceTime = new TimeSpan(0, 11, 0, 0, 0),
                            TrackName = "Dhahran"
                        },
                        new
                        {
                            RaceId = "race20",
                            RaceDate = new DateTime(2007, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "Claiming Stake",
                            RaceTime = new TimeSpan(0, 8, 30, 0, 0),
                            TrackName = "Jeddah"
                        },
                        new
                        {
                            RaceId = "race21",
                            RaceDate = new DateTime(2007, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "3-year-old colts",
                            RaceTime = new TimeSpan(0, 14, 30, 0, 0),
                            TrackName = "Riyadh"
                        },
                        new
                        {
                            RaceId = "race22",
                            RaceDate = new DateTime(2007, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "Handicap",
                            RaceTime = new TimeSpan(0, 15, 0, 0, 0),
                            TrackName = "Dhahran"
                        },
                        new
                        {
                            RaceId = "race23",
                            RaceDate = new DateTime(2007, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "3-year-old fillies",
                            RaceTime = new TimeSpan(0, 9, 30, 0, 0),
                            TrackName = "Jeddah"
                        },
                        new
                        {
                            RaceId = "race24",
                            RaceDate = new DateTime(2007, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "3-year-old colts",
                            RaceTime = new TimeSpan(0, 13, 30, 0, 0),
                            TrackName = "Jubail"
                        },
                        new
                        {
                            RaceId = "race25",
                            RaceDate = new DateTime(2007, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "Claiming Stake",
                            RaceTime = new TimeSpan(0, 10, 0, 0, 0),
                            TrackName = "Jeddah"
                        },
                        new
                        {
                            RaceId = "race26",
                            RaceDate = new DateTime(2007, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "3-year-old colts",
                            RaceTime = new TimeSpan(0, 12, 30, 0, 0),
                            TrackName = "Yanbu"
                        },
                        new
                        {
                            RaceId = "race27",
                            RaceDate = new DateTime(2007, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "Handicap",
                            RaceTime = new TimeSpan(0, 14, 0, 0, 0),
                            TrackName = "Dubai"
                        },
                        new
                        {
                            RaceId = "race28",
                            RaceDate = new DateTime(2007, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "2-year-old fillies",
                            RaceTime = new TimeSpan(0, 8, 30, 0, 0),
                            TrackName = "Jeddah"
                        },
                        new
                        {
                            RaceId = "race29",
                            RaceDate = new DateTime(2007, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "3-year-old colts",
                            RaceTime = new TimeSpan(0, 8, 0, 0, 0),
                            TrackName = "Bahrain"
                        },
                        new
                        {
                            RaceId = "race30",
                            RaceDate = new DateTime(2007, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "Claiming Stake",
                            RaceTime = new TimeSpan(0, 9, 30, 0, 0),
                            TrackName = "Dhahran"
                        },
                        new
                        {
                            RaceId = "race31",
                            RaceDate = new DateTime(2007, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "Handicap",
                            RaceTime = new TimeSpan(0, 9, 0, 0, 0),
                            TrackName = "Dhahran"
                        },
                        new
                        {
                            RaceId = "race32",
                            RaceDate = new DateTime(2007, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "2-year-old colts",
                            RaceTime = new TimeSpan(0, 11, 0, 0, 0),
                            TrackName = "Jubail"
                        },
                        new
                        {
                            RaceId = "race33",
                            RaceDate = new DateTime(2007, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "Claiming Stake",
                            RaceTime = new TimeSpan(0, 13, 0, 0, 0),
                            TrackName = "Bahrain"
                        },
                        new
                        {
                            RaceId = "race34",
                            RaceDate = new DateTime(2007, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "3-year-old colts",
                            RaceTime = new TimeSpan(0, 12, 0, 0, 0),
                            TrackName = "Dubai"
                        },
                        new
                        {
                            RaceId = "race35",
                            RaceDate = new DateTime(2007, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "Handicap",
                            RaceTime = new TimeSpan(0, 10, 30, 0, 0),
                            TrackName = "Dubai"
                        },
                        new
                        {
                            RaceId = "race36",
                            RaceDate = new DateTime(2007, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaceName = "3-year-old colts",
                            RaceTime = new TimeSpan(0, 14, 30, 0, 0),
                            TrackName = "Jeddah"
                        });
                });

            modelBuilder.Entity("Backend.Models.RaceResults", b =>
                {
                    b.Property<string>("RaceId")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("HorseId")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<float?>("Prize")
                        .HasPrecision(10, 2)
                        .HasColumnType("float");

                    b.Property<string>("Results")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("RaceId", "HorseId");

                    b.HasIndex("HorseId");

                    b.ToTable("RaceResults");

                    b.HasData(
                        new
                        {
                            RaceId = "race1",
                            HorseId = "horse3",
                            Prize = 500000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race1",
                            HorseId = "horse11",
                            Prize = 200000f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race1",
                            HorseId = "horse15",
                            Prize = 500000f,
                            Results = "third"
                        },
                        new
                        {
                            RaceId = "race2",
                            HorseId = "horse6",
                            Prize = 100000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race2",
                            HorseId = "horse2",
                            Prize = 50000f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race2",
                            HorseId = "horse20",
                            Prize = 20000f,
                            Results = "third"
                        },
                        new
                        {
                            RaceId = "race3",
                            HorseId = "horse22",
                            Prize = 70000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race3",
                            HorseId = "horse5",
                            Prize = 50000f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race3",
                            HorseId = "horse1",
                            Prize = 20000f,
                            Results = "third"
                        },
                        new
                        {
                            RaceId = "race4",
                            HorseId = "horse19",
                            Prize = 50000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race4",
                            HorseId = "horse18",
                            Prize = 0f,
                            Results = "no show"
                        },
                        new
                        {
                            RaceId = "race4",
                            HorseId = "horse14",
                            Prize = 0f,
                            Results = "no show"
                        },
                        new
                        {
                            RaceId = "race6",
                            HorseId = "horse25",
                            Prize = 5000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race7",
                            HorseId = "horse7",
                            Prize = 2000f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race9",
                            HorseId = "horse11",
                            Prize = 0f,
                            Results = "last"
                        },
                        new
                        {
                            RaceId = "race10",
                            HorseId = "horse18",
                            Prize = 500f,
                            Results = "fourth"
                        },
                        new
                        {
                            RaceId = "race11",
                            HorseId = "horse12",
                            Prize = 50000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race11",
                            HorseId = "horse17",
                            Prize = 25000f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race11",
                            HorseId = "horse21",
                            Prize = 10000f,
                            Results = "fourth"
                        },
                        new
                        {
                            RaceId = "race12",
                            HorseId = "horse14",
                            Prize = 6000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race12",
                            HorseId = "horse18",
                            Prize = 5000f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race13",
                            HorseId = "horse25",
                            Prize = 100000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race13",
                            HorseId = "horse4",
                            Prize = 50000f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race13",
                            HorseId = "horse12",
                            Prize = 30000f,
                            Results = "third"
                        },
                        new
                        {
                            RaceId = "race14",
                            HorseId = "horse23",
                            Prize = 25000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race14",
                            HorseId = "horse26",
                            Prize = 20000f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race15",
                            HorseId = "horse11",
                            Prize = 10000f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race15",
                            HorseId = "horse24",
                            Prize = 8000f,
                            Results = "third"
                        },
                        new
                        {
                            RaceId = "race16",
                            HorseId = "horse10",
                            Prize = 5000f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race16",
                            HorseId = "horse14",
                            Prize = 4000f,
                            Results = "third"
                        },
                        new
                        {
                            RaceId = "race17",
                            HorseId = "horse7",
                            Prize = 15000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race17",
                            HorseId = "horse10",
                            Prize = 1100f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race18",
                            HorseId = "horse6",
                            Prize = 70000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race19",
                            HorseId = "horse22",
                            Prize = 1000000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race19",
                            HorseId = "horse1",
                            Prize = 80000f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race19",
                            HorseId = "horse8",
                            Prize = 60000f,
                            Results = "third"
                        },
                        new
                        {
                            RaceId = "race20",
                            HorseId = "horse23",
                            Prize = 1500f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race20",
                            HorseId = "horse14",
                            Prize = 1000f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race20",
                            HorseId = "horse26",
                            Prize = 800f,
                            Results = "third"
                        },
                        new
                        {
                            RaceId = "race20",
                            HorseId = "horse10",
                            Prize = 500f,
                            Results = "fourth"
                        },
                        new
                        {
                            RaceId = "race21",
                            HorseId = "horse24",
                            Prize = 70000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race21",
                            HorseId = "horse15",
                            Prize = 55000f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race21",
                            HorseId = "horse3",
                            Prize = 40000f,
                            Results = "third"
                        },
                        new
                        {
                            RaceId = "race22",
                            HorseId = "horse18",
                            Prize = 10000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race22",
                            HorseId = "horse19",
                            Prize = 8000f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race23",
                            HorseId = "horse25",
                            Prize = 150000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race24",
                            HorseId = "horse7",
                            Prize = 10000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race25",
                            HorseId = "horse10",
                            Prize = 8000f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race25",
                            HorseId = "horse20",
                            Prize = 2000f,
                            Results = "fourth"
                        },
                        new
                        {
                            RaceId = "race26",
                            HorseId = "horse24",
                            Prize = 8000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race26",
                            HorseId = "horse20",
                            Prize = 2000f,
                            Results = "fourth"
                        },
                        new
                        {
                            RaceId = "race27",
                            HorseId = "horse18",
                            Prize = 70000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race27",
                            HorseId = "horse23",
                            Prize = 40000f,
                            Results = "third"
                        },
                        new
                        {
                            RaceId = "race28",
                            HorseId = "horse25",
                            Prize = 90000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race29",
                            HorseId = "horse15",
                            Prize = 80000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race29",
                            HorseId = "horse3",
                            Prize = 65000f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race29",
                            HorseId = "horse24",
                            Prize = 50000f,
                            Results = "third"
                        },
                        new
                        {
                            RaceId = "race30",
                            HorseId = "horse14",
                            Prize = 1500f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race30",
                            HorseId = "horse10",
                            Prize = 500f,
                            Results = "fourth"
                        },
                        new
                        {
                            RaceId = "race31",
                            HorseId = "horse7",
                            Prize = 90000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race31",
                            HorseId = "horse26",
                            Prize = 70000f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race31",
                            HorseId = "horse23",
                            Prize = 50000f,
                            Results = "third"
                        },
                        new
                        {
                            RaceId = "race31",
                            HorseId = "horse10",
                            Prize = 30000f,
                            Results = "fourth"
                        },
                        new
                        {
                            RaceId = "race32",
                            HorseId = "horse22",
                            Prize = 150000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race32",
                            HorseId = "horse13",
                            Prize = 125000f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race32",
                            HorseId = "horse16",
                            Prize = 100000f,
                            Results = "third"
                        },
                        new
                        {
                            RaceId = "race33",
                            HorseId = "horse23",
                            Prize = 1700f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race33",
                            HorseId = "horse26",
                            Prize = 1200f,
                            Results = "third"
                        },
                        new
                        {
                            RaceId = "race34",
                            HorseId = "horse11",
                            Prize = 50000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race34",
                            HorseId = "horse15",
                            Prize = 30000f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race35",
                            HorseId = "horse7",
                            Prize = 45000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race35",
                            HorseId = "horse19",
                            Prize = 25000f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race36",
                            HorseId = "horse11",
                            Prize = 100000f,
                            Results = "first"
                        },
                        new
                        {
                            RaceId = "race36",
                            HorseId = "horse15",
                            Prize = 80000f,
                            Results = "second"
                        },
                        new
                        {
                            RaceId = "race36",
                            HorseId = "horse20",
                            Prize = 50000f,
                            Results = "third"
                        });
                });

            modelBuilder.Entity("Backend.Models.Stable", b =>
                {
                    b.Property<string>("StableId")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Colors")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Location")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("StableName")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("StableId");

                    b.ToTable("Stables");

                    b.HasData(
                        new
                        {
                            StableId = "stable1",
                            Colors = "orange",
                            Location = "Riyadh",
                            StableName = "Zobair Farm"
                        },
                        new
                        {
                            StableId = "stable2",
                            Colors = "kiwi",
                            Location = "Dubai",
                            StableName = "Zayed Farm"
                        },
                        new
                        {
                            StableId = "stable3",
                            Colors = "cinnamon",
                            Location = "Jeddah",
                            StableName = "Zahra Farm"
                        },
                        new
                        {
                            StableId = "stable4",
                            Colors = "lemon",
                            Location = "Jubail",
                            StableName = "Sunny Stables"
                        },
                        new
                        {
                            StableId = "stable5",
                            Colors = "lemon",
                            Location = "Ajman",
                            StableName = "Ajman Stables"
                        },
                        new
                        {
                            StableId = "stable6",
                            Colors = "bright blue",
                            Location = "Dubai",
                            StableName = "Dubai Stables"
                        });
                });

            modelBuilder.Entity("Backend.Models.Track", b =>
                {
                    b.Property<string>("TrackName")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("TrackName");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            TrackName = "Doha",
                            Length = 20,
                            Location = "QT"
                        },
                        new
                        {
                            TrackName = "Jubail",
                            Length = 15,
                            Location = "SA"
                        },
                        new
                        {
                            TrackName = "Yanbu",
                            Length = 18,
                            Location = "SA"
                        },
                        new
                        {
                            TrackName = "Dubai",
                            Length = 17,
                            Location = "UE"
                        },
                        new
                        {
                            TrackName = "Jeddah",
                            Length = 19,
                            Location = "SA"
                        },
                        new
                        {
                            TrackName = "Bahrain",
                            Length = 18,
                            Location = "BH"
                        },
                        new
                        {
                            TrackName = "Sharjah",
                            Length = 20,
                            Location = "UE"
                        },
                        new
                        {
                            TrackName = "Riyadh",
                            Length = 22,
                            Location = "SA"
                        },
                        new
                        {
                            TrackName = "Dhahran",
                            Length = 20,
                            Location = "SA"
                        });
                });

            modelBuilder.Entity("Backend.Models.Trainer", b =>
                {
                    b.Property<string>("TrainerId")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("FName")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("LName")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("StableId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("TrainerId");

                    b.HasIndex("StableId");

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            TrainerId = "trainer1",
                            FName = "Fahd",
                            LName = "Mohammed",
                            StableId = "stable2"
                        },
                        new
                        {
                            TrainerId = "trainer2",
                            FName = "Saeed",
                            LName = "Saleh",
                            StableId = "stable1"
                        },
                        new
                        {
                            TrainerId = "trainer3",
                            FName = "Raad",
                            LName = "Ali",
                            StableId = "stable4"
                        },
                        new
                        {
                            TrainerId = "trainer4",
                            FName = "Wasim",
                            LName = "Sayed",
                            StableId = "stable3"
                        },
                        new
                        {
                            TrainerId = "trainer5",
                            FName = "Ali",
                            LName = "Ahmed",
                            StableId = "stable3"
                        },
                        new
                        {
                            TrainerId = "trainer6",
                            FName = "Salah",
                            LName = "Faisal",
                            StableId = "stable5"
                        },
                        new
                        {
                            TrainerId = "trainer7",
                            FName = "Ahmed",
                            LName = "Hamid",
                            StableId = "stable6"
                        },
                        new
                        {
                            TrainerId = "trainer8",
                            FName = "Ahmed",
                            LName = "Khalid",
                            StableId = "stable6"
                        });
                });

            modelBuilder.Entity("Backend.Models.Horse", b =>
                {
                    b.HasOne("Backend.Models.Stable", "Stable")
                        .WithMany("Horses")
                        .HasForeignKey("StableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stable");
                });

            modelBuilder.Entity("Backend.Models.Owns", b =>
                {
                    b.HasOne("Backend.Models.Horse", "Horse")
                        .WithMany("Owns")
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Owner", "Owner")
                        .WithMany("Owns")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Horse");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Backend.Models.Race", b =>
                {
                    b.HasOne("Backend.Models.Track", "Track")
                        .WithMany("Races")
                        .HasForeignKey("TrackName");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Backend.Models.RaceResults", b =>
                {
                    b.HasOne("Backend.Models.Horse", "Horse")
                        .WithMany("RaceResults")
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Race", "Race")
                        .WithMany("RaceResults")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Horse");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Backend.Models.Trainer", b =>
                {
                    b.HasOne("Backend.Models.Stable", "Stable")
                        .WithMany("Trainers")
                        .HasForeignKey("StableId");

                    b.Navigation("Stable");
                });

            modelBuilder.Entity("Backend.Models.Horse", b =>
                {
                    b.Navigation("Owns");

                    b.Navigation("RaceResults");
                });

            modelBuilder.Entity("Backend.Models.Owner", b =>
                {
                    b.Navigation("Owns");
                });

            modelBuilder.Entity("Backend.Models.Race", b =>
                {
                    b.Navigation("RaceResults");
                });

            modelBuilder.Entity("Backend.Models.Stable", b =>
                {
                    b.Navigation("Horses");

                    b.Navigation("Trainers");
                });

            modelBuilder.Entity("Backend.Models.Track", b =>
                {
                    b.Navigation("Races");
                });
#pragma warning restore 612, 618
        }
    }
}
